Develop
Seven730/LifeShare pull request #18
Opened 2020-04-14 08:46 UTC by Seven730

Merge develop with master

2020-04-14 14:49 UTC, jacekku requested changes
Nazywajmy komponenty funkcyjne z dużej litery jak klasy, będzie bardziej spójnie. Tak jak masz NavigationBar i później importujesz w innych to nie musisz z małej litery pisać :)

2020-04-14 14:49 UTC, jacekku commented on src/Components/NavigationBar.jsx
> +          <Nav.Link href="post" style={{ color: "gold" }}>
może nie dawajmy stylów inline?

2020-04-14 15:24 UTC, Seven730 commented on src/Components/NavigationBar.jsx
> +          <Nav.Link href="post" style={{ color: "gold" }}>
temporary to jest, ale się zgadzam :)

2020-04-15 10:37 UTC, Seven730 commented
Dodany nowy content i poprawiłem zgodnie z uwagami

2020-04-15 16:41 UTC, merged